<?php
/**
 * @file
 * ding_video.module
 */

/**
 * Implements hook_field_widget_properties_alter().
 */
function ding_video_field_widget_properties_alter(&$widget, $context) {
  if ($widget['module'] == 'media' && $context['entity_type'] == 'node') {
    $widget['settings']['allowed_types']['video'] = 'video';
  }
}

/**
 * Implements hook_node_view().
 */
function ding_video_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full') {
    $media_field = field_view_field("node", $node, "field_{$node->type}_title_image");

    foreach ($media_field['#items'] as $key => $item) {
      if ($item['type'] == 'video') {
        $fid = $item['fid'];

        $display['settings'] = [
          'width' => '640',
          'height' => '390',
          'autohide' => 2,
          'autoplay' => 0,
          'color' => 'red',
          'enablejsapi' => 0,
          'loop' => 0,
          'modestbranding' => 0,
          'nocookie' => 0,
          'origin' => '',
          'protocol' => 'https:',
          'protocol_specify' => 0,
          'rel' => 1,
          'showinfo' => 1,
          'theme' => 'dark',
          'captions' => FALSE,
          'controls' => FALSE,
        ];

        $file = file_load($fid);
        $scheme = file_uri_scheme($file->uri);

        switch ($scheme) {
          case 'youtube':
            module_load_include('inc', 'media_youtube', '/includes/media_youtube.formatters.inc');
            $render_array = media_youtube_file_formatter_video_view($file, $display, LANGUAGE_NONE);
            $node->content["field_{$node->type}_title_image"][$key] = $render_array;
            break;

          case 'vimeo':
            module_load_include('inc', 'media_vimeo', '/includes/media_vimeo.formatters.inc');

            $display['settings']['api'] = 1;
            $display['settings']['byline'] = 1;
            $display['settings']['title'] = $file->filename;
            $display['settings']['portrait'] = 1;

            $render_array = media_vimeo_file_formatter_video_view($file, $display, LANGUAGE_NONE);
            $node->content["field_{$node->type}_title_image"][$key] = $render_array;
            break;

          case 'public':
            $render_array = [
              '#theme' => 'file_entity_file_video',
              '#files' => [$item],
              '#controls' => TRUE,
              '#autoplay' => FALSE,
              '#loop' => FALSE,
              '#muted' => FALSE,
              '#width' => NULL,
              '#height' => NULL,
              '#preload' => NULL,
            ];

            $node->content["field_{$node->type}_title_image"][$key] = $render_array;
            break;
        }
      }
    }
  }

  drupal_add_js(drupal_get_path('module', 'ding_video') . '/js/ding_video.js', 'file');
  drupal_add_css(drupal_get_path('module', 'ding_video') . '/css/ding_video.css');
}

/**
 * Implements hook_form_alter().
 *
 * Disabling manualcrop processing for attached video files.
 */
function ding_video_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node_edit_form']) && $form['#node_edit_form'] == TRUE) {
    $content_types = [
      'ding_news',
      'ding_event',
      'ding_eresource',
      'ding_page',
    ];

    $node = isset($form['#node']) ? $form['#node'] : FALSE;

    $image_field_types = ['list_image', 'title_image'];
    if ($node && in_array($node->type, $content_types)) {
      foreach ($image_field_types as $image_field_type) {
        $field_name = "field_{$node->type}_{$image_field_type}";

        if (isset($node->{$field_name})) {
          // Existing node editing.
          if (!empty($form_state['values'])) {
            foreach ($form_state['values'][$field_name][LANGUAGE_NONE] as $key => $item) {
              $file = file_load($item['fid']);
              if ($file->type == 'video') {
                unset($form[$field_name][LANGUAGE_NONE][$key]['#process'][2]);
              }
            }
          }
          else {
            foreach ($node->{$field_name}[LANGUAGE_NONE] as $key => $item) {
              if (!empty($item['type'])) {
                if ($item['type'] == 'video') {
                  unset($form[$field_name][LANGUAGE_NONE][$key]['#process'][2]);
                }
              }
            }
          }
        }
        elseif (isset($form_state['values'][$field_name])) {
          // New node creation.
          foreach ($form_state['values'][$field_name][LANGUAGE_NONE] as $key => $item) {
            $file = file_load($item['fid']);
            if ($file->type == 'video') {
              unset($form[$field_name][LANGUAGE_NONE][$key]['#process'][2]);
            }
          }
        }
      }
    }
  }
}
